dist: xenial

matrix: 
        include:
                - language: c
                  compiler: clang
                  install:
                          - make test
                  script:
                          - ./build/softtest/test
                - language: c
                  compiler: gcc
                  install:
                          - make test
                  script:
                          - ./build/softtest/test
                - language: c
                  compiler: gcc
                  script:
                          - make cov
                  after_success:
                          - bash <(curl -s https://codecov.io/bash)

