dist: xenial

matrix: 
        include:
                - language: c
                  compiler: clang
                  script:
                          - make run
                - language: c
                  compiler: gcc
                  script:
                          - make run
                - language: c
                  compiler: gcc
                  script:
                          - make cov
                  after_success:
                          - bash <(curl -s https://codecov.io/bash)

